version: '3.7'

services:
  db:
    container_name: db
    image: mysql:latest
    tty: true
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "people"
    ports:
      - "3306:3306"
    # you can comment the volumes if you don't want to persist the data
    # saved in mysql in your pc
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - internal

networks:
  internal:
    driver: bridge
